/*
data.js - contains an array of charity objects. 
Exports the array as 'cdb'
If you want to include this in another file (in the same directory) copy the following lines of code: 

var cArray = require('./data.js')
var cdb = cArray.cdb;

This will allow you to access the array by calling 'cdb' in that file. 
*/

var charityArray = [{ charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } }
]


module.exports.cdb = charityArray;
