/*
data.js - contains an array of charity objects. 
Exports the array as 'cdb'
If you want to include this in another file (in the same directory) copy the following lines of code: 

var cArray = require('./data.js')
var cdb = cArray.cdb;

This will allow you to access the array by calling 'cdb' in that file. 
*/

var charityArray = [
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=4482&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Advocating for justice and equality',
    charityName: 'Southern Poverty Law Center',
    ein: '630598743',
    mission: 'The Southern Poverty Law Center (SPLC) was founded in 1971 as a small civil rights law firm. Today, SPLC is internationally known for its tolerance education programs, its legal victories against white supremacists and its tracking of hate groups. Throughout its history, SPLC has worked to make the nation\'s Constitutional ideals a reality. The SPLC legal department fights all forms of discrimination and works to protect society\'s most vulnerable members, handling innovative cases that few lawyers are willing to take. The SPLC Intelligence Project monitors hate groups and tracks extremist activity throughout the U.S. To combat the causes of hate, SPLC in 1991 established Teaching Tolerance, an educational program to help K-12 teachers foster respect and understanding in the classroom.',
    websiteURL: 'http://www.splcenter.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/international.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=8&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human and Civil Rights',
       categoryID: 8 },
    cause: 
     { causeID: 21,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=8&cuid=21&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Advocacy and Education',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/advocacy.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Crime, Legal-Related',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: 'Public Interest Law, Litigation',
       deductibilityDetail: null,
       nteeCode: 'I83',
       nteeLetter: 'I' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'AL',
       city: 'Montgomery',
       postalCode: '36104    ',
       streetAddress1: '400 Washington Avenue',
       streetAddress2: null },
    currentRating: 
     { score: 85.5,
       financial: 79.72,
       transparency: 97.00,
       ratingID: 124354,
       publicationDate: '2017-10-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=8985&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Restoring Families & Giving Hope',
    charityName: 'Durham Rescue Mission',
    ein: '581482590',
    mission: 'The Durham Rescue Mission is a faith-based, non-profit organization. Our primary goal is to share the gospel of Jesus Christ and His redemptive work on the cross. The Durham Rescue Mission is achieving this goal as we minister to the homeless and addicted in central North Carolina. Our Mission is to meet through the power of Jesus Christ the needs of the whole person: spiritual, educational, emotional, physical, social, and vocational, so that those who are hurting may become fully functioning members of society.',
    websiteURL: 'http://www.durhamrescuemission.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 28,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=28&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Homeless Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/homeless.jpg' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Church 170(b)(1)(A)(i)',
       nteeSuffix: null,
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: null,
       nteeLetter: '0' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NC',
       city: 'Durham',
       postalCode: '27703',
       streetAddress1: 'P.O. Box 11858',
       streetAddress2: null },
    currentRating: 
     { score: 100,
	   financial: 100,
       transparency: 100,
       ratingID: 127046,
       publicationDate: '2017-12-22T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=15774&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: '40 Years of Inspiring, Educating, Connecting.',
    charityName: 'BestPrep',
    ein: '411265355',
    mission: 'BestPrep is a statewide nonprofit organization with a mission to prepare students with business, career, and financial literacy skills through hands-on experiences that inspire success in work and life. BestPrep\'s programs engage 4-12 grade students and their educators in active learning, while connecting them to the world outside the classroom. With the help of more than 4,000 professional volunteers each year, BestPrep bridges classroom curriculum and the business community, enriching the teaching and learning experience for students and educators.',
    websiteURL: 'http://bestprep.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: null,
       nteeLetter: '0' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'MN',
       city: 'Brooklyn Park',
       postalCode: '55428',
       streetAddress1: '7100 Northland Circle N.',
       streetAddress2: 'Suite 120' },
    currentRating: 
     { score: 87.15,
       financial: 83.24,
       transparency: 93.00,
       ratingID: 123392,
       publicationDate: '2017-08-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6613&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Bringing joy and warmth to disadvantaged children and their families',
    charityName: 'Association to Benefit Children',
    ein: '133303089',
    mission: 'Association to Benefit Children (ABC) is dedicated to bringing joy and warmth to disadvantaged children and their families through compassionate, sustainable, comprehensive and integrated services, designed to permanently break the cycles of abuse, neglect, sickness and homelessness. ABC\'s humane and innovative programs include early educational advocacy, housing assistance, mental health services, family support and preservation, crisis intervention, therapeutic out-of-school and summer day camp programs, youth leadership development and mentoring.',
    websiteURL: 'http://www.a-b-c.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 17,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Children\'s and Family Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: 'P34',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10028',
       streetAddress1: '419 East 86th Street',
       streetAddress2: null },
    currentRating: 
     { score: 95.59,
       financial: 93.77,
       transparency: 100,
       ratingID: 126859,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=4788&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'We\'re for youth development, healthy living and social responsibility.',
    charityName: 'YMCA of Greater Seattle',
    ein: '910482710',
    mission: 'Mission: Building a community where all people, especially the young, are encouraged to develop their fullest potential in spirit, mind and body.Our Cause: Strengthening community is our cause. The Y makes accessible the support and opportunities that empower people to learn, grow and thrive - and we\'ve done this since 1876.Our neighbors in King and south Snohomish counties work with us to deliver positive change to over 200,000 people each year. With your help we make sure that people in need have access to opportunities at our 13 branches and two residential camps.The Y is dedicated to responsible stewardship of your generous donations. We are efficient and effective. With your help, we provide measurable impact.',
    websiteURL: 'http://www.seattleymca.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 15,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=15&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Multipurpose Human Service Organizations',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/multipurpose.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Human Services - Multipurpose and Other',
       foundationStatus: 'Organization that normally receives no more than one-third of its support from gross investment income and unrelated business income and at the same time more than one-third of its support from contributions, fees, and gross receipts related to exempt purposes.  509(a)(2)',
       nteeSuffix: '0',
       nteeClassification: 'Young Men\'s or Women\'s Associations (YMCA, YWCA, YWHA, YMHA)',
       deductibilityDetail: null,
       nteeCode: 'P27',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'WA',
       city: 'Seattle',
       postalCode: '98104    ',
       streetAddress1: '909 Fourth Avenue',
       streetAddress2: null },
    currentRating: 
     { score: 90.52,
       financial: 92.36,
       transparency: 89.00,
       ratingID: 126691,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=17469&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Educating and empowering women',
    charityName: 'Akilah Institute for Women',
    ein: '260770655',
    mission: 'Akilah Institute for Women offers a unique model of market-relevant education that enables young women to achieve economic independence and obtain leadership roles in the workplace and in society. Akilah aims to build future generations of women leaders and professionals in East Africa through the development of a network of campuses. Akilah Institute for Women attracts and welcomes bright, motivated women from diverse countries throughout the East African Region and beyond. Students from Uganda, Burundi, and Kenya have joined our Institute, and the number of international students continues to rise.',
    websiteURL: 'https://www.akilahinstitute.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Philanthropy, Voluntarism and Grantmaking Foundations',
       foundationStatus: 'Organization that normally receives no more than one-third of its support from gross investment income and unrelated business income and at the same time more than one-third of its support from contributions, fees, and gross receipts related to exempt purposes.  509(a)(2)',
       nteeSuffix: null,
       nteeClassification: 'Philanthropy, Voluntarism, and Grantmaking Foundations N.E.C.',
       deductibilityDetail: null,
       nteeCode: 'T99',
       nteeLetter: 'T' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'Brooklyn',
       postalCode: '11201',
       streetAddress1: '195 Plymouth Street',
       streetAddress2: 'Suite 2/4' },
    currentRating: 
     { score: 83.35,
       financial: 86.10,
       transparency: 81.00,
       ratingID: 125311,
       publicationDate: '2017-11-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=15448&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Raising the Bar',
    charityName: 'Legal Outreach',
    ein: '133214627',
    mission: 'Legal Outreach prepares urban youth from underserved communities in New York City to compete at high academic levels by using intensive legal and educational programs as tools for fostering vision, developing skills, enhancing confidence, and facilitating the pursuit of higher education. We use law to attract junior high school students to academic programs that inspire and motivate them to strive for academic success. From the 8th through 12th grades, students work after school, on weekends, and during summers to build the skills and confidence they need to achieve their goals. Once in college, students who wish to pursue law school are eligible to participate in our College to Law School Pipeline Diversity Program.',
    websiteURL: 'http://legaloutreach.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: null,
       nteeLetter: '0' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'Long Island City',
       postalCode: '11106',
       streetAddress1: '36-14 35th Street',
       streetAddress2: null },
    currentRating: 
     { score: 89.92,
       financial: 85.75,
       transparency: 100,
       ratingID: 129351,
       publicationDate: '2018-03-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=13856&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Helping thousands of low-income students',
    charityName: 'Bottom Line',
    ein: '043351427',
    mission: 'Bottom Line is dedicated to helping disadvantaged students get in to college, graduate from college, and go far in life. We achieve this mission by providing low-income and first-generation students with one-on-one guidance through the application process and during college. Since 1997, Bottom Line has addressed the low college graduation rates of at-risk urban youth. Our organization was founded on the belief that students need a mentor and a guide during the college application process and throughout college to succeed. By providing consistent one-on-one support, Bottom Line has helped thousands of low-income and first-generation students stay in college and complete their degrees',
    websiteURL: 'http://www.bottomline.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Community Improvement, Capacity Building',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: 'Community Improvement, Capacity Building N.E.C.',
       deductibilityDetail: null,
       nteeCode: 'S99',
       nteeLetter: 'S' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'MA',
       city: 'Jamaica Plain',
       postalCode: '02130',
       streetAddress1: '500 Amory Street',
       streetAddress2: 'Suite 3' },
    currentRating: 
     { score: 88.89,
       financial: 84.81,
       transparency: 96.00,
       ratingID: 123253,
       publicationDate: '2017-08-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=16554&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Committed to eliminating the barriers faced by underrepresented people of color in science, technology, engineering and math.',
    charityName: 'Level Playing Field Institute',
    ein: '912088635',
    mission: 'Founded in 2001, Level Playing Field Institute is committed to eliminating the barriers faced by underrepresented people of color in science, technology, engineering and math (STEM) and fostering their untapped talent for the advancement of our nation. We envision a world where a true level playing field exists – a world where everyone has equitable access to opportunities, including the historically disenfranchised. LPFI provides the resources and support to ensure that underrepresented students of color throughout our nation can overcome barriers and obstacles to their success and thrive in STEM fields of study, from K-12 through higher education.',
    websiteURL: 'http://www.lpfi.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Social Science Research Institutes, Services',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: 'Labor Studies',
       deductibilityDetail: null,
       nteeCode: 'V37',
       nteeLetter: 'V' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'CA',
       city: 'Oakland',
       postalCode: '94612',
       streetAddress1: '2148 Broadway',
       streetAddress2: null },
    currentRating: 
     { score: 77.96,
       financial: 72.69,
       transparency: 85.00,
       ratingID: 100140,
       publicationDate: '2017-06-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 2,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=6082&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Opening the door to greater educational opportunities since 1963',
    charityName: 'A Better Chance',
    ein: '237173492',
    mission: 'A Better Chance is the oldest and only national organization of its kind changing the life trajectory for academically talented youth of color via access to rigorous and prestigious educational opportunities for students in grades 6-12. Founded in 1963, our mission is to increase substantially the number of well-educated young people of color who are capable of assuming positions of responsibility and leadership in American society. We carry out our mission through our signature College Preparatory Schools Program, which annually recruits, refers and supports about 500 scholars at more than 300 member schools in 29 states. More than 13,000 alumni have now gone on to distinguished careers as physicians, artists, educators, lawyers, politicians and corporate executives.',
    websiteURL: 'http://www.abetterchance.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: null,
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: null,
       deductibilityDetail: null,
       nteeCode: null,
       nteeLetter: '0' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10001',
       streetAddress1: '253 West 35th Street',
       streetAddress2: '6th Floor' },
    currentRating: 
     { score: 71.46,
	   financial: 66.17,
       transparency: 78.00,
       ratingID: 125632,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 2,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=4452&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Supporting the Seattle Public Library',
    charityName: 'The Seattle Public Library Foundation',
    ein: '911140642',
    mission: 'The Seattle Public Library Foundation was established in 1980 by a group of far-sighted citizens who understood that a great Library wouldn\'t be possible through public funding alone. The Foundation has continued its original vision of generating private-sector support to supplement tax-based funding. The result has been improved collections, expanded programs, and enhanced services. The Foundation\'s fund-raising efforts focus on three key areas: collections, programs, and facilities. With funding from The Seattle Public Library Foundation, the Library can offer a wide range of innovative programs and resources.',
    websiteURL: 'http://foundation.spl.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/arts.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=2&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Arts, Culture, Humanities',
       categoryID: 2 },
    cause: 
     { causeID: 6,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=2&cuid=6&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Libraries, Historical Societies and Landmark Preservation',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/libraries.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Educational Institutions and Related Activities',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: '6',
       nteeClassification: 'Single Organization Support ',
       deductibilityDetail: null,
       nteeCode: 'B11',
       nteeLetter: 'B' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'WA',
       city: 'Seattle',
       postalCode: '98104',
       streetAddress1: '1000 Fourth Avenue',
       streetAddress2: null },
    donationAddress: 
     { country: null,
       stateOrProvince: 'WA',
       city: 'Seattle',
       postalCode: '98124',
       streetAddress1: 'PO Box 3951',
       streetAddress2: null },
    currentRating: 
     { score: 98.12,
       financial: 97.35,
       transparency: 100,
       ratingID: 119532,
       publicationDate: '2017-05-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=12702&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'The art of inspiring education.',
    charityName: 'DreamYard Project',
    ein: '133759661',
    mission: 'DreamYard collaborates with Bronx youth, families and schools to build pathways to equity and opportunity through the arts.DreamYard programs develop artistic voice, nurture young peoples\' desire to make change and cultivate the skills necessary to reach positive goals. By committing to sustained learning opportunities along an educational pathway, we support young people as they work toward higher learning, meaningful careers and social action. We believe that young people in the Bronx need a continuous set of supports to help them towards positive outcomes as they navigate their educational pathway. We have every expectation that through offering sustained and meaningful supports our youth will develop the tools to become creative and engaged citizens, life-long learners and the leaders and innovators of the 21st century.',
    websiteURL: 'http://www.dreamyard.com',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Arts, Culture and Humanities',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: '0',
       nteeClassification: 'Arts Education',
       deductibilityDetail: null,
       nteeCode: 'A25',
       nteeLetter: 'A' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'Bronx',
       postalCode: '10456',
       streetAddress1: '1085 Washington Avenue',
       streetAddress2: 'Ground Floor' },
    currentRating: 
     { score: 89.99,
       financial: 91.11,
       transparency: 89.00,
       ratingID: 127729,
       publicationDate: '2017-12-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=12842&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'The greatest casualty is being forgotten',
    charityName: 'Wounded Warrior Project',
    ein: '202370934',
    mission: 'The mission of Wounded Warrior Project is to honor and empower wounded warriors. Our purpose is: to raise awareness and enlist the public\'s aid for the needs of severely injured service men and women; to help severely injured service members aid and assist each other; and to provide unique, direct programs and services to meet the needs of severely injured service members.',
    websiteURL: 'http://www.woundedwarriorproject.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 29,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=29&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Social Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/social_services.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Human Services - Multipurpose and Other',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: null,
       nteeClassification: 'Emergency Assistance (Food, Clothing, Cash)',
       deductibilityDetail: null,
       nteeCode: 'P60',
       nteeLetter: 'P' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'FL',
       city: 'Jacksonville',
       postalCode: '32256',
       streetAddress1: '4899 Belfort Road',
       streetAddress2: 'Suite 300' },
    donationAddress: 
     { country: null,
       stateOrProvince: 'KS',
       city: 'Topeka',
       postalCode: '66675',
       streetAddress1: 'P.O. Box 758517',
       streetAddress2: null },
    currentRating: 
     { score: 88.67,
       financial: 84.27,
       transparency: 97,
       ratingID: 129709,
       publicationDate: '2018-02-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=15876&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Providing Bible history education to public schools',
    charityName: 'Bible in the Schools',
    ein: '620523361',
    mission: 'Bible in the Schools provides Bible history education to public schools. Bible in the Schools aims to enrich the next generation with the wisdom and knowledge of the Bible by developing curriculum, training, and financial resources for elective, for-credit courses in Bible history, using the Bible as a text, taught in a controlled curriculum by trained and certified middle and high school teachers employed by the Hamilton County Department of education. Teachers are employees of Hamilton County Department of Education, and Bible in the Schools reimburses HCDE for teacher salaries and benefits.',
    websiteURL: 'http://www.bibleintheschools.com/www',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/community-development.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=3&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Education',
       categoryID: 3 },
    cause: 
     { causeID: 40,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Youth Education Programs and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Educational Institutions and Related Activities',
       foundationStatus: 'School 170(b)(1)(A)(ii)',
       nteeSuffix: 'G',
       nteeClassification: 'Elementary, Secondary Education, K - 12',
       deductibilityDetail: null,
       nteeCode: 'B20',
       nteeLetter: 'B' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'TN',
       city: 'Chattanooga',
       postalCode: '37405',
       streetAddress1: '243 Signal Mountain Road',
       streetAddress2: 'Suite 113' },
    donationAddress: 
     { country: null,
       stateOrProvince: 'TN',
       city: 'Chattanooga',
       postalCode: '37405',
       streetAddress1: 'P.O. Box 4228',
       streetAddress2: null },
    currentRating: 
     { score: 85.68,
      financial: 83.00,
       transparency: 89.00,
       ratingID: 119172,
       publicationDate: '2017-04-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=14859&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Providing food security and community connections to our neighbors in need.',
    charityName: 'West Seattle Food Bank',
    ein: '911464412',
    mission: 'Founded in 1988, West Seattle Food Bank\'s (WSFB) mission is to provide food security and community connections to our neighbors in need. WSFB distributes food, baby food, baby supplies, books and other items to low-income residents of West Seattle. The WSFB has many partners assisting to secure food that will meet the special dietary needs and cultural preferences of the diverse population we serve. WSFB also collaborates to offer food distributions at other non-profit agencies in the area.',
    websiteURL: 'http://www.westseattlefoodbank.org/',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/health.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=6&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human Services',
       categoryID: 6 },
    cause: 
     { causeID: 18,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=18&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Food Banks, Food Pantries, and Food Distribution',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/food_banks.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Food, Agriculture and Nutrition',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: 'Z',
       nteeClassification: 'Food Banks, Food Pantries',
       deductibilityDetail: null,
       nteeCode: 'K31',
       nteeLetter: 'K' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'WA',
       city: 'Seattle',
       postalCode: '98126',
       streetAddress1: '3419 Southwest Morgan Street',
       streetAddress2: null },
    currentRating: 
     { score: 88.58,
       financial: 88.18,
       transparency: 89.00,
       ratingID: 120218,
       publicationDate: '2017-05-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=3286&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'We are their voice',
    charityName: 'American Society for the Prevention of Cruelty to Animals',
    ein: '131623829',
    mission: 'Founded in 1866, the American Society for the Prevention of Cruelty to Animals (ASPCA) was the first humane organization established in the Americas, and today has more than one million supporters throughout North America. The ASPCA\'s mission is to provide effective means for the prevention of cruelty to animals throughout the United States. The ASPCA provides local and national leadership in animal-assisted therapy, animal behavior, animal poison control, anti-cruelty, humane education, legislative services, and shelter outreach. The New York City headquarters houses a full-service, accredited animal hospital, adoption center, and mobile clinic outreach program. The Humane Law Enforcement department enforces New York\'s animal cruelty laws.',
    websiteURL: 'http://www.aspca.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/animals.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=1&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Animals',
       categoryID: 1 },
    cause: 
     { causeID: 2,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=1&cuid=2&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Animal Rights, Welfare, and Services',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/animal_rights.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Animal-Related',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: '0',
       nteeClassification: 'Animal Protection and Welfare',
       deductibilityDetail: null,
       nteeCode: 'D20',
       nteeLetter: 'D' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10128    ',
       streetAddress1: '424 East 92nd Street',
       streetAddress2: null },
    currentRating: 
     { score: 83.75,
       financial: 77.22,
       transparency: 97.00,
       ratingID: 129819,
       publicationDate: '2018-03-01T05:00:00.000Z',
       ratingImage: [Object],
       rating: 3,
       _rapid_links: [Object] } },
  { charityNavigatorURL: 'https://www.charitynavigator.org/?bay=search.summary&orgid=3247&utm_source=DataAPI&utm_content=0b43a724',
    tagLine: 'Because freedom can\'t protect itself',
    charityName: 'American Civil Liberties Union Foundation',
    ein: '136213516',
    mission: 'The American Civil Liberties Union (ACLU) Foundation is the arm of the ACLU that conducts litigation and communication efforts. The Foundation provides legal presentation in cases involving issues of civil liberties and constitutional rights ranging from administrative hearings to trials and appeals. In addition, the Foundation educates the public as to civil liberties and constitutional rights by disseminating literature and other publications. The ACLU Foundation preserves and promotes civil rights and liberties as guaranteed by the United States Constitution.',
    websiteURL: 'http://www.aclu.org',
    activeAdvisories: { _rapid_links: [Object] },
    removedAdvisories: { _rapid_links: [Object] },
    category: 
     { image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/categories/international.png',
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.categories&categoryid=8&utm_source=DataAPI&utm_content=0b43a724',
       categoryName: 'Human and Civil Rights',
       categoryID: 8 },
    cause: 
     { causeID: 21,
       charityNavigatorURL: 'https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=8&cuid=21&utm_source=DataAPI&utm_content=0b43a724',
       causeName: 'Advocacy and Education',
       image: 'https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/advocacy.gif' },
    irsClassification: 
     { deductibility: 'Contributions are deductible',
       subsection: '501(c)(3)',
       nteeType: 'Civil Rights, Social Action, Advocacy',
       foundationStatus: 'Organization which receives a substantial part of its support from a governmental unit or the general public   170(b)(1)(A)(vi)',
       nteeSuffix: '0',
       nteeClassification: 'Civil Liberties Advocacy',
       deductibilityDetail: null,
       nteeCode: 'R60',
       nteeLetter: 'R' },
    mailingAddress: 
     { country: null,
       stateOrProvince: 'NY',
       city: 'New York',
       postalCode: '10004    ',
       streetAddress1: '125 Broad Street',
       streetAddress2: '18th Floor' },
    currentRating: 
     { score: 94.07,
       financial: 92.64,
       transparency: 96.00,
       ratingID: 119467,
       publicationDate: '2017-06-01T04:00:00.000Z',
       ratingImage: [Object],
       rating: 4,
       _rapid_links: [Object] } } ]

       module.exports.cdb = charityArray;
       //console.log(charityArray[3].charityNavigatorURL);
